[2025-10-01T03:44:53.817+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-01T03:44:53.845+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_churn_model.train scheduled__2025-09-30T02:00:00+00:00 [queued]>
[2025-10-01T03:44:53.849+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_churn_model.train scheduled__2025-09-30T02:00:00+00:00 [queued]>
[2025-10-01T03:44:53.849+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-01T03:44:53.866+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train> on 2025-09-30 02:00:00+00:00
[2025-10-01T03:44:53.874+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=78549) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-01T03:44:53.875+0000] {standard_task_runner.py:64} INFO - Started process 78623 to run task
[2025-10-01T03:44:53.875+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'train_churn_model', 'train', 'scheduled__2025-09-30T02:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/train_churn_model.py', '--cfg-path', '/tmp/tmpt57gr1a4']
[2025-10-01T03:44:53.876+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask train
[2025-10-01T03:44:53.938+0000] {task_command.py:426} INFO - Running <TaskInstance: train_churn_model.train scheduled__2025-09-30T02:00:00+00:00 [running]> on host ab51105a0306
[2025-10-01T03:44:54.021+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='train_churn_model' AIRFLOW_CTX_TASK_ID='train' AIRFLOW_CTX_EXECUTION_DATE='2025-09-30T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-30T02:00:00+00:00'
[2025-10-01T03:44:54.025+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-01T03:44:55.858+0000] {logging_mixin.py:188} WARNING - 2025/10/01 03:44:55 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-10-01T03:45:04.963+0000] {python.py:237} INFO - Done. Returned value was: {'model_path': '/opt/project/models/latest_model.pkl', 'val_auc': 0.5325090909090909, 'val_f1': 0.1814516129032258}
[2025-10-01T03:45:04.965+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-01T03:45:05.001+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=train_churn_model, task_id=train, run_id=scheduled__2025-09-30T02:00:00+00:00, execution_date=20250930T020000, start_date=20251001T034453, end_date=20251001T034505
[2025-10-01T03:45:05.056+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-01T03:45:05.089+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-01T03:45:05.092+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
