[2025-09-30T22:16:34.582+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-30T22:16:34.612+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_churn_model.preprocess scheduled__2025-09-29T02:00:00+00:00 [queued]>
[2025-09-30T22:16:34.615+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_churn_model.preprocess scheduled__2025-09-29T02:00:00+00:00 [queued]>
[2025-09-30T22:16:34.616+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-30T22:16:34.625+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): preprocess> on 2025-09-29 02:00:00+00:00
[2025-09-30T22:16:34.635+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'train_churn_model', 'preprocess', 'scheduled__2025-09-29T02:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/train_churn_model.py', '--cfg-path', '/tmp/tmplpuf3xk8']
[2025-09-30T22:16:34.637+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask preprocess
[2025-09-30T22:16:34.639+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=18577) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-30T22:16:34.643+0000] {standard_task_runner.py:64} INFO - Started process 18646 to run task
[2025-09-30T22:16:34.698+0000] {task_command.py:426} INFO - Running <TaskInstance: train_churn_model.preprocess scheduled__2025-09-29T02:00:00+00:00 [running]> on host ab51105a0306
[2025-09-30T22:16:34.845+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='train_churn_model' AIRFLOW_CTX_TASK_ID='preprocess' AIRFLOW_CTX_EXECUTION_DATE='2025-09-29T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-29T02:00:00+00:00'
[2025-09-30T22:16:34.850+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-30T22:16:34.896+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-30T22:16:34.896+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/train_churn_model.py", line 12, in step_preprocess
    preprocess(DATA_PATH, "/opt/project/data/processed/train.parquet", "/opt/project/data/processed/val.parquet")
  File "/opt/project/src/data_prep.py", line 5, in preprocess
    df = pd.read_csv(raw_csv)
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/project/data/fleet_churn.csv'
[2025-09-30T22:16:34.907+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=train_churn_model, task_id=preprocess, run_id=scheduled__2025-09-29T02:00:00+00:00, execution_date=20250929T020000, start_date=20250930T221634, end_date=20250930T221634
[2025-09-30T22:16:34.921+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task preprocess ([Errno 2] No such file or directory: '/opt/project/data/fleet_churn.csv'; 18646)
[2025-09-30T22:16:34.955+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-30T22:16:34.978+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-30T22:16:34.987+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
